name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Pack
        run: dotnet pack --configuration Debug --version-suffix dev-${{ github.run_number }} --output ./packages
      - name: Configure NuGet source for GitHub Packages
        run: dotnet nuget add source --username yamaoto --password ${{ secrets.NUGET_PACKAGE_TOKEN  }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/yamaoto/index.json" --skip-duplicate
      - name: Push NuGet packages into GitHub Packages
        run: dotnet nuget push "./packages/*.nupkg" --source "github"
      - name: Push NuGet packages into NuGet.org
        run: dotnet nuget push "./packages/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_ORG_PACKAGE_TOKEN }} --skip-duplicate
